# Generated by Django 2.0.2 on 2018-08-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
