# Generated by Django 2.0.2 on 2018-08-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0002_prompt_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
