# Generated by Django 2.0.2 on 2018-08-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='addedBy',
            field=models.TextField(blank=True),
        ),
    ]
